#
# in addition to the functionality specific toml config the
# following tables are also populated at runtime from cli
# args and build time information.
#
# both cli and build subtables should not be populated manually

# [build]
#   project = @CMAKE_PROJECT_NAME@
#   install-dir = @CMAKE_INSTALL_PREFIX@
#   sysconf-dir = @CMAKE_INSTALL_FULL_SYSCONFDIR@
#   data-dir = @CMAKE_INSTALL_FULL_DATADIR@
#
# cli notes:
#   -all cli table entries have default values if not specified
#   -cfg-path is the path containing cfg-dir
#   -cfg-dir is the combination of build.sysconf-dir and cli-dir 

# [cli]
#   cfg-path = <build.sysconf-dir>
#   cfg-dir = live
#   daemon = false
#   dmx-host = "dmx" 
#   force-restart = false
#   log-file = "/var/log/pierre/pierre.log" 
#   pid-file = "/run/pierre/pierre.log"
#   parent_path = "" # parent path of the executable
