##
## Pierre Configuration
##

[desk]
threads = 3

[desk.dmx_ctrl]
local = { stalled.ms = 10_500, resolve = { timeout.ms = 15_000, retry.ms = 60_000 } }
# remote = { host = "dmx", idle_shutdown_ms = 10_000, stats.ms = 2_000 }
remote = { host = "dmx-test", idle_shutdown.ms = 10_000, stats.ms = 2_000 }

[desk.dimmable]
max = 8190
min = 0 # note: min is unused, all values calculated using max
bright = 1.0
units = [
  { name = "el dance", addr = 2, max = 0.25, min = 0.01, dim = 0.03, pulse = { start = 0.5, end = 0.25 } },
  { name = "el entry", addr = 3, max = 0.25, min = 0.01, dim = 0.03, pulse = { state = 0.15, end = 0.03 } },
  { name = "led forest", addr = 4, dim = 0.005, pulse = { start = 0.02, end = 0.005 } },
  { name = "disco ball", addr = 1, dim = 0.65, pulse = { start = 0.65, end = 0.85 } },
]

[desk.pinspot]
units = [
  { name = "main pinspot", addr = 1, frame_len = 6 },
  { name = "fill pinspot", addr = 7, frame_len = 6 },
]

[desk.switch]
units = [{ name = "ac power", addr = 1 }]

[frame]
cipher = { buffer_size = 0x2000 } # bytes (4k)
dsp = { threads = 2 } # percentage 1-100 (num threads = (hw_concurrency * factor) / 100

[frame.clock]
host = "127.0.0.1"              # nqptp host
shm_name = "/nqptp"             # path to nqptp shared memory directory

# UNUSED:  need implementation
# [frame.peaks.magnitudes] # only keep peaks in this range
# floor = 0.9
# ceiling = 128.0

[fx.majorpeak]
silence = { timeout = { seconds = 20 } }

[fx.majorpeak.frequencies]
hard = { floor = 40.0, ceiling = 11500.0 }
soft = { floor = 115.0, ceiling = 1000.0 }

[fx.majorpeak.magnitudes]
floor = 2.17
ceiling = 80.0

[fx.majorpeak.makecolors.above_soft_ceiling]
hue = { min = 300.0, max = 360.0, step = 0.5 }
bri = { max = 85.0, mag_scaled = true }

[fx.majorpeak.makecolors.generic]
hue = { min = 0.1, max = 3400.0, step = 0.1 }
bri = { max = 100.0, mag_scaled = true }

[[fx.majorpeak.pinspots]]
name = "fill pinspot"
type = "fill"
fade_max_ms = 1200
freq_max = 5000.0
when_greater = { freq = 180.0, bri_min = 20.0, when_higher_freq = { bri_min = 85.0 } }
when_less_than = { freq = 180.0, bri_min = 30.0 }

[[fx.majorpeak.pinspots]]
name = "main pinspot"
type = "main"
fade_max_ms = 800
freq_min = 160.0
when_fading = { bri_min = 10.0, when_freq_greater = { bri_min = 30.0 } }
when_less_than = { freq = 160.0, bri_min = 30.0 }

[fx.standby]
color = { hue = 0.0, sat = 100.0, bri = 50.0 }
hue_step = 0.65
silence = { timeout = { minutes = 57 }, suggested_fx_next = "all_stop" }

[logger]
# category specific overrides
debug = false   # show any debug messages?
init = true     # always log init messages from any module, when true
threads = true  # show any thread messages?
shutdown = true # show any shutdown messages?
async = true

[logger.conf.watch]
check = false
initiate = false
initiate_watch = true
latest = false

[logger.desk]
thread = true
resume = true
shutdown = true
standby = true
next_reel = false

[logger.desk.dmx_ctrl]
run = true
host = { connect = true, resolve = true, unknown = true }

[logger.desk.racked]
flush = false
log = true
next_reel = true

[logger.desk.reel]
flush = false

[logger.frame]
anchor = false
av = false
clock = { init = true, shutdown = false,  peers_update = false,  map_shm = false }
dsp = { init = true }
decipher = false

[logger.fx]
major_peak = { execute = false }
silence_watch = false
standby = { apply_config = false}

[logger.mdns]
start = true

[logger.mdns.ctx]
all_for_now = true
browse = true 
cb_client = true
cb_browse = true
cb_evt_grp = false
resolved = false

[logger.rtsp]
audio = true
ctx = true
init = true
info = true
event = false
net = false
reply = { build = false, info = true }

[mdns]
port = 7000
receiver = "Pierre Devel" # specify %h to use hostname
service = "_ruth._tcp"    # service advertised by rendering devices

[rtsp]
audio = { buffer_size = { bytes = 0x800000 } }
connection = { timeout_ms = 30_000 }
saver = { enable = false, file = "/tmp/rtsp.log", format = "raw " }

[stats]
enabled = true
db_uri = "http://localhost:8086?db=pierre"
batch_of = 150