
[desk.dmx_ctrl]
local = { stalled.ms = 10_500, resolve = { timeout.ms = 15_000, retry.ms = 60_000 } }
# remote = { host = "dmx", idle_shutdown_ms = 10_000, stats.ms = 2_000 }
remote = { host = "dmx-test", idle_shutdown.ms = 10_000, stats.ms = 2_000 }
threads = 1

[desk.dimmable]
max = 8190
min = 0 # note: min is unused, all values calculated using max
bright = 1.0
units = [
  { name = "el dance", addr = 2, max = 0.25, min = 0.01, dim = 0.03, pulse = { start = 0.5, end = 0.25 } },
  { name = "el entry", addr = 3, max = 0.25, min = 0.01, dim = 0.03, pulse = { state = 0.15, end = 0.03 } },
  { name = "led forest", addr = 4, dim = 0.005, pulse = { start = 0.02, end = 0.005 } },
  { name = "disco ball", addr = 1, dim = 0.65, pulse = { start = 0.65, end = 0.85 } },
]

[desk.pinspot]
units = [
  { name = "main pinspot", addr = 1, frame_len = 6 },
  { name = "fill pinspot", addr = 7, frame_len = 6 },
]

[desk.switch]
units = [{ name = "ac power", addr = 1 }]