[fx.majorpeak]
silence = { timeout = { seconds = 20 } }

[fx.majorpeak.frequencies]
hard = { floor = 40.0, ceiling = 11500.0 }
soft = { floor = 115.0, ceiling = 1000.0 }

[fx.majorpeak.magnitudes]
floor = 2.17
ceiling = 80.0

[fx.majorpeak.makecolors.above_soft_ceiling]
hue = { min = 300.0, max = 360.0, step = 0.5 }
bri = { max = 85.0, mag_scaled = true }

[fx.majorpeak.makecolors.generic]
hue = { min = 0.1, max = 3400.0, step = 0.1 }
bri = { max = 100.0, mag_scaled = true }

[[fx.majorpeak.pinspots]]
name = "fill pinspot"
type = "fill"
fade_max_ms = 1200
freq_max = 5000.0
when_greater = { freq = 180.0, bri_min = 20.0, when_higher_freq = { bri_min = 85.0 } }
when_less_than = { freq = 180.0, bri_min = 30.0 }

[[fx.majorpeak.pinspots]]
name = "main pinspot"
type = "main"
fade_max_ms = 800
freq_min = 160.0
when_fading = { bri_min = 10.0, when_freq_greater = { bri_min = 30.0 } }
when_less_than = { freq = 160.0, bri_min = 30.0 }

[fx.standby]
color = { hue = 0.0, sat = 100.0, bri = 50.0 }
hue_step = 0.65
silence = { timeout = { minutes = 57 }, suggested_fx_next = "all_stop" }
