
[logger]
# category specific overrides
debug = false   # show any debug messages?
init = true     # always log init messages from any module, when true
threads = true  # show any thread messages?
shutdown = true # show any shutdown messages?
async = true

[logger.config.watch]
check_file = false
register = true
unregister = false

[logger.config.token]
notify = true

[logger.desk]
thread = true
resume = true
shutdown = true
standby = true
next_reel = false

[logger.desk.dmx_ctrl]
run = true
host = { connect = true, resolve = true, unknown = true }

[logger.desk.racked]
flush = true
monitor_wip = true
log = true

[logger.desk.reel]
flush = false

[logger.frame]
anchor = false
av = false
clock = { init = true, shutdown = false, peers_update = false, thread = true, map_shm = false }
# clock_info = false
dsp = { init = true }
decipher = false

[logger.fx]
major_peak = { execute = false }
silence_watch = false
standby = { apply_config = false}

[logger.mdns]
start = true

[logger.mdns.ctx]
all_for_now = true
browse = true 
cb_client = true
cb_browse = true
cb_evt_grp = false
resolved = false

[logger.rtsp]
audio = true
ctx = true
init = true
info = true
event = false
net = false
reply = { build = false, info = true }
