[pierre]
title = "Pierre Live"
version = 2
working_dir = ".pierre"

[mdns]
receiver = "%h"           # use hostname
dmx_service = "_ruth.tcp"

[frame]
dsp = { concurrency_factor = 0.4 }
clock = { shm_name = "/nqptp" }

[desk]
service = "_ruth._tcp"
colorbars = true

[fx.majorpeak.color]
reference = { hue = 0.0, sat = 100.0, bri = 100.0 }

[fx.majorpeak.frequencies]
hard = { floor = 40.0, ceiling = 10000.0 }
soft = { floor = 110.0, ceiling = 11500.0 }

[fx.majorpeak.makecolors.above_soft_ceiling]
hue = { min = 345.0, max = 355.0, step = 0.0001 }
bri = { max = 50.0, mag_scaled = true }

[fx.majorpeak.makecolors.generic]
hue = { min = 30.0, max = 360.0, step = 0.0001 }
bri = { max = 100.0, mag_scaled = true }

[[fx.majorpeak.pinspots]]
name = "fill"
freq_max = 1000.0
fade_max_ms = 800
when_greater = { freq = 180.0, bri_min = 3.0, when_higher_freq = { bri_min = 80.0 } }
when_lessthan = { freq = 180.0, bri_min = 27.0 }

[[fx.majorpeak.pinspots]]
name = "main"
freq_min = 180.0
fade_max_ms = 700
when_fading = { bri_min = 5.0, when_freq_greater = { bri_min = 69.0 } }

[peaks.magnitudes]
floor = 2.0
ceiling = 32.0
