[base]
title = "Pierre Live"   # for identification purposes
config_vsn = 2          # config file format
working_dir = ".pierre" # cwd to this directory at startup
# build_vsn = ""        # (runtime) git version of executable
# build_time = ""       # (runtime) datetime of build

[cli]
# NOTE: cli table is not a source of config, rather it holds
#       command line opts passed at startup and populated
#       at runtime
#
# app_name = "" # typically basename() of the app
# cfg_file = "" # could be this file or another specified by cli opt

[stats]
enabled = true
db_uri = "http://localhost:8086?db=pierre"
batch_of = 100

[debug]
path = "../extra/debug"
rtsp = { save = false, file = "rtsp.log" }

[dmx]
# controller = "dmx"
controller = "test-with-devs"

[dmx.timeouts]
connect_ms = 1000
idle_ms = 60_000
retry_ms = 500
stalled_ms = 2000

[mdns]
receiver = "%h"        # use hostname
service = "_ruth._tcp" # service advertised by rendering devices

[rtsp]
audio = { buffer_size = 0x800000 } # in bytes (8mb)

[frame]
dsp = { concurrency_factor = 0.5 } # num threads (hw_concurrency * factor)
cipher_buffer = 0x2000             # in bytes (4k)

[frame.clock]
shm_name = "/nqptp"
info = { max_wait_frames = 10 }

[frame.racked]
threads = 3 # stats runs on this io_ctx

[frame.peaks.magnitudes] # only keep peaks in this rangethreads = 3
floor = 0.9
ceiling = 128.0

[desk]
colorbars = true
threads = 5      # frame, dmx connect, dmx ctrl/data

[fx.leave]
color = { hue = 0.0, sat = 100.0, bri = 50.0 }
hue_step = 0.65

[fx.majorpeak.frequencies]
hard = { floor = 40.0, ceiling = 11500.0 }
soft = { floor = 110.0, ceiling = 5000.0 }

[fx.majorpeak.magnitudes]
floor = 2.09
ceiling = 80.0

[fx.majorpeak.makecolors.above_soft_ceiling]
hue = { min = 225.0, max = 355.0, step = 0.0001 }
bri = { max = 55.0, mag_scaled = true }

[fx.majorpeak.makecolors.generic]
hue = { min = 0.0, max = 360.0, step = 0.0001 }
bri = { max = 100.0, mag_scaled = true }

[[fx.majorpeak.pinspots]]
name = "fill pinspot"
type = "fill"
fade_max_ms = 1199
freq_max = 5000.0
when_greater = { freq = 180.0, bri_min = 27.0, when_higher_freq = { bri_min = 85.0 } }
when_less_than = { freq = 180.0, bri_min = 13.0 }

[[fx.majorpeak.pinspots]]
name = "main pinspot"
type = "main"
fade_max_ms = 900
freq_min = 180.0
when_fading = { bri_min = 5.0, when_freq_greater = { bri_min = 27.0 } }
when_less_than = { freq = 180.0, bri_min = 17.0 }

[fx.units]
power = [{ name = "ac power", address = 0 }]
pinspots = [{ name = "main pinspot", address = 0 }, { name = "fill pinspot", address = 7 }]
elwire = [{ name = "el entry", address = 3 }, { name = "el dance", address = 2 }]
led_forest = [{ name = "led forest", address = 4 }]
disco_ball = [{ name = "disco ball", address = 1 }]
