[base]
title = "Pierre Live"   # for identification purposes
config_vsn = 2          # config file format
working_dir = ".pierre" # cwd to this directory at startup
# build_vsn = ""        # git version of executable populated at runtime
# build_time = ""       # datetime of build

[cli]
# NOTE: cli table is not a source of config, rather it holds
#       command line opts passed at startup and populated
#       at runtime
#
# app_name = "" # typically basename() of the app
# cfg_file = "" # could be this file or another specified by cli opt

[mdns]
receiver = "%h"                   # use hostname
service = "_ruth._tcp"            # service advertised by rendering devices
dmx_controller = "test-with-devs" # rendering device to use

[frame]
dsp = { concurrency_factor = 0.5 } # num threads (hw_concurrency * factor)
clock = { shm_name = "/nqptp" }

[frame.peaks.magnitudes] # only keep peaks in this range
floor = 0.9
ceiling = 128.0

[desk]
colorbars = true
threads = 6

[fx.majorpeak.color]
reference = { hue = 0.0, sat = 100.0, bri = 100.0 }

[fx.majorpeak.frequencies]
hard = { floor = 40.0, ceiling = 10000.0 }
soft = { floor = 110.0, ceiling = 11500.0 }

[fx.majorpeak.magnitudes]
floor = 2.009
ceiling = 64.0

[fx.majorpeak.makecolors.above_soft_ceiling]
hue = { min = 345.0, max = 355.0, step = 0.0001 }
bri = { max = 50.0, mag_scaled = true }

[fx.majorpeak.makecolors.generic]
hue = { min = 30.0, max = 360.0, step = 0.0001 }
bri = { max = 100.0, mag_scaled = true }

[[fx.majorpeak.pinspots]]
name = "fill pinspot"
freq_max = 1000.0
fade_max_ms = 800
when_greater = { freq = 180.0, bri_min = 3.0, when_higher_freq = { bri_min = 80.0 } }
when_lessthan = { freq = 180.0, bri_min = 27.0 }

[[fx.majorpeak.pinspots]]
name = "main pinspot"
freq_min = 180.0
fade_max_ms = 700
when_fading = { bri_min = 5.0, when_freq_greater = { bri_min = 69.0 } }
