[base]
title = "Pierre Live"   # for identification purposes
config_vsn = 2          # config file format
working_dir = ".pierre" # cwd to this directory at startup
# build_vsn = ""        # (runtime) git version of executable
# build_time = ""       # (runtime) datetime of build

[cli]
# NOTE: cli table is not a source of config, rather it is populated
#       at runtime based on command line opts and shell environmeny
#
# app_name = "" # typically basename() of the app
# cfg_file = "" # could be this file or another specified by cli opt
# exec_path = "" # executable path
# parent_path = "" # parent path of the executable

[stats]
enabled = true
db_uri = "http://localhost:8086?db=pierre"
batch_of = 150

[info]
path = "../extra/debug"
desk = { dmx_ctrl = true, reel = false }
frames = { av = false, flush = false, racked = false }
mdns = { ctx = { cb_client = true, cb_browse = false, cb_evt_grp = true } }

# category specific
init = true
threads = true
debug = false

[info.rtsp]
audio = false
ctx = { teardown = true }
event = false
file = "rtsp.log"
format = "pretty"
reply = false
save = false
server = true
session = true

[dmx]
# controller = "dmx" # DEFAULT
# controller = "test-with-devs"

[dmx.timeouts.milliseconds]
idle = 60_000
stalled = 5100

[mdns]
port = 7000
receiver = "Pierre"    # specify %h to use hostname
service = "_ruth._tcp" # service advertised by rendering devices

[rtsp]
audio = { buffer_size = 0x800000 }   # bytes (8mb)
connection = { timeout_ms = 30_000 }
threads = 2

[frame]
cipher = { buffer_size = 0x2000 }  # bytes (4k)
dsp = { concurrency_factor = 0.5 } # num threads (hw_concurrency * factor)

[frame.clock]
host = "127.0.0.1"              # nqptp host
info = { min_wait_frames = 12 } # wait frames before returning no clock
shm_name = "/nqptp"             # path to nqptp shared memory directory
threads = 1

[frame.racked]
threads = 3

[frame.peaks.magnitudes] # only keep peaks in this range
floor = 0.9
ceiling = 128.0

[desk]
threads = 3 # frame, dmx connect, dmx ctrl/data

[desk.dimmable]
max = 8190
min = 0 # note: min is unused, all values calculated using max
bright = 1.0
units = [
  { name = "el dance", addr = 2, max = 0.25, min = 0.01, dim = 0.03, pulse = { start = 0.5, end = 0.25 } },
  { name = "el entry", addr = 3, max = 0.25, min = 0.01, dim = 0.03, pulse = { state = 0.15, end = 0.03 } },
  { name = "led forest", addr = 4, dim = 0.005, pulse = { start = 0.02, end = 0.005 } },
  { name = "disco ball", addr = 1, dim = 0.65, pulse = { start = 0.65, end = 0.85 } },
]

[desk.pinspot]
units = [
  { name = "main pinspot", addr = 1, frame_len = 6 },
  { name = "fill pinspot", addr = 7, frame_len = 6 },
]

[desk.switch]
units = [{ name = "ac power", addr = 1 }]

[fx.standby]
color = { hue = 0.0, sat = 100.0, bri = 50.0 }
hue_step = 0.65
silence = { timeout = { minutes = 30, suggested_fx_next = "all_stop" } }
will_render = true

[fx.majorpeak]
will_render = true

[fx.majorpeak.silence]
timeout = { seconds = 13, suggested_fx_next = "standby" }

[fx.majorpeak.frequencies]
hard = { floor = 40.0, ceiling = 11500.0 }
soft = { floor = 110.0, ceiling = 5000.0 }

[fx.majorpeak.magnitudes]
floor = 2.15
ceiling = 80.0

[fx.majorpeak.makecolors.above_soft_ceiling]
hue = { min = 225.0, max = 355.0, step = 0.0001 }
bri = { max = 55.0, mag_scaled = true }

[fx.majorpeak.makecolors.generic]
hue = { min = 0.0, max = 360.0, step = 0.0001 }
bri = { max = 100.0, mag_scaled = true }

[[fx.majorpeak.pinspots]]
name = "fill pinspot"
type = "fill"
fade_max_ms = 1500
freq_max = 5000.0
when_greater = { freq = 220.0, bri_min = 20.0, when_higher_freq = { bri_min = 85.0 } }
when_less_than = { freq = 220.0, bri_min = 25.0 }

[[fx.majorpeak.pinspots]]
name = "main pinspot"
type = "main"
fade_max_ms = 1000
freq_min = 180.0
when_fading = { bri_min = 30.0, when_freq_greater = { bri_min = 27.0 } }
when_less_than = { freq = 180.0, bri_min = 30.0 }
