[pierre]
title = "Pierre Basic Config"
version = 1
working_dir = "/tmp/pierre"

[dmx]
host = "test-with-devs.ruth"
port = "48005"

[dsp]
fft = {samples = 1024, rate = 48000}
logging = {file = "dsp.log", enable = false, truncate = true}

[lightdesk]
colorbars = false
logging = {file = "majorpeak.log", peaks = false, colors = false, truncate = true}

[lightdesk.majorpeak.color]
reference = { hue = 0.0, sat = 100.0, bri = 100.0}
random_start = false
rotate = {enable = false, ms = 7000}

[lightdesk.majorpeak.frequencies]
hard = {ceiling = 10000.0, floor = 40.0}
soft = {ceiling = 1500.0, floor = 110.0}

[lightdesk.majorpeak.pinspot.fill]
name = 'fill'
fade = {max_ms = 500}
freq0 = { range = {min = 220.0, max = 10000.0}, brightness = {min = 30.0}}
freq1 = { range = {min = 0.0, max = 220.0}, brightness = {min = 30.0}}

[lightdesk.majorpeak.pinspot.main]
name = 'main'
fade = {max_ms = 500}
frequency_min = 180.0
brightness = { priority_when_less = 42.0, minimum = 10 }

[lightdesk.majorpeak.makecolor.above_soft_ceiling]
hue = {min = 345.0, max = 355.0, step = 0.0001}
brightness = {max = 50.0, mag_scaled = true}

[lightdesk.majorpeak.makecolor.generic]
hue = {min = 10.0, max = 360.0, step = 0.0001}

[pcm.logging]
file = "pcm.log"
init = false
truncate = true

[pcm.alsa]
device = 'hw:CARD=sndrpihifiberry,DEV=0'
format = "S16_LE"
channels = 2
rate = 48000
avail_min = 128
